apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - harbor.baojiliu.xyz
      port:
        name: https-443
        number: 8443
        protocol: HTTPS
      tls:
        credentialName: baojiliu-xyz
        mode: SIMPLE
